version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "stage"
    schedule:
      interval: "weekly"
    labels:
      - "actions dependencies"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "stage"
    schedule:
      interval: "weekly"
    labels:
      - "npm dependencies"